In [1]:
import pandas as pd

1. Загрузите датафрейм из файла polit.csv и сохраните его в переменную polit. Если в
датафрейме есть строки с пропущенными значениями, то удалите их.

In [3]:
df = pd.read_csv("polit.csv")
df = df.dropna()
df

,Unnamed: 0,ctry,fh09,polity09,gini,fparl08,mena,lati,cari,east,sovi,afri,corr0509
1,1,Albania,3.0,9.0,33.0,7.14,0,0,0,0,1,0,-0.580513
2,2,Algeria,5.5,2.0,35.3,6.48,1,0,0,0,0,0,-0.434654
5,5,Angola,5.5,-2.0,58.6,37.27,0,0,0,0,0,0,-1.292684
7,7,Argentina,2.0,8.0,48.8,39.76,0,1,0,0,0,0,-0.420793
8,8,Armenia,5.0,5.0,30.2,8.40,0,0,0,0,0,0,-0.578211
...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,206,"Venezuela, RB",4.5,-3.0,43.4,18.56,0,1,0,0,0,0,-1.061680
207,207,Vietnam,6.0,-7.0,37.8,25.76,0,0,0,1,0,0,-0.656128
210,210,"Yemen, Rep.",5.5,-2.0,37.7,0.73,1,0,0,0,0,0,-0.808840
211,211,Zambia,3.5,7.0,50.7,15.19,0,0,0,0,0,1,-0.601142
212,212,Zimbabwe,6.0,1.0,50.1,18.15,0,0,0,0,0,1,-1.382121

2. Выберите в датафрейме строки, которые соответствуют странам со значениями
индекса Freedom House (fh09) выше 5.

In [6]:
df[df["fh09"] > 5]

,Unnamed: 0,ctry,fh09,polity09,gini,fparl08,mena,lati,cari,east,sovi,afri,corr0509
2,2,Algeria,5.5,2.0,35.3,6.48,1,0,0,0,0,0,-0.434654
5,5,Angola,5.5,-2.0,58.6,37.27,0,0,0,0,0,0,-1.292684
12,12,Azerbaijan,5.5,-7.0,16.8,11.38,0,0,0,0,0,0,-1.026767
17,17,Belarus,6.5,-7.0,28.8,32.53,0,0,0,0,0,0,-0.765586
31,31,Cambodia,5.5,2.0,44.2,15.76,0,0,0,1,0,0,-1.151233
32,32,Cameroon,6.0,-4.0,44.6,13.89,0,0,0,0,0,1,-1.000362
37,37,Chad,6.5,-2.0,39.8,5.16,0,0,0,0,0,1,-1.346880
40,40,China,6.5,-7.0,41.5,21.33,0,0,0,1,0,0,-0.568752
43,43,"Congo, Dem. Rep.",6.0,5.0,44.4,7.73,0,0,0,0,0,1,-1.428074
44,44,"Congo, Rep.",5.5,-4.0,47.3,9.18,0,0,0,0,0,1,-1.113118
46,46,Cote d'Ivoire,5.5,0.0,48.4,8.87,0,0,0,0,0,1,-1.198933
56,56,"Egypt, Arab Rep.",5.5,-3.0,32.1,3.68,1,0,0,0,0,0,-0.579147
67,67,Gabon,5.5,3.0,41.5,16.11,0,0,0,0,0,1,-0.856973
88,88,"Iran, Islamic Rep.",6.0,-7.0,38.3,2.80,1,0,0,0,0,0,-0.600917
89,89,Iraq,5.5,0.0,38.3,25.45,1,0,0,0,0,0,-1.462697
96,96,Jordan,5.5,-3.0,37.7,8.48,1,0,0,0,0,0,0.349112
97,97,Kazakhstan,5.5,-6.0,30.9,12.34,0,0,0,0,0,0,-0.937653
104,104,Kyrgyz Republic,5.5,1.0,33.5,25.56,0,0,0,0,0,0,-1.174855
105,105,Lao PDR,6.5,-7.0,32.6,25.22,0,0,0,1,0,0,-1.206055
123,123,Mauritania,5.5,-2.0,39.0,19.87,0,0,0,0,0,1,-0.537831
157,157,Qatar,5.5,-10.0,41.1,0.00,1,0,0,0,0,0,1.148954
159,159,Russian Federation,5.5,4.0,43.7,11.47,0,0,0,0,0,0,-0.917829
160,160,Rwanda,5.5,-3.0,46.7,50.94,0,0,0,0,0,1,-0.164223
182,182,Swaziland,6.0,-9.0,50.7,22.11,0,0,0,0,0,1,-0.310528
186,186,Tajikistan,5.5,-3.0,33.6,19.59,0,0,0,0,0,0,-1.006135
193,193,Tunisia,6.0,-4.0,40.8,19.93,1,0,0,0,0,0,0.005451
204,204,Uzbekistan,7.0,-9.0,36.7,16.36,0,0,0,0,0,0,-1.071779
207,207,Vietnam,6.0,-7.0,37.8,25.76,0,0,0,1,0,0,-0.656128
210,210,"Yemen, Rep.",5.5,-2.0,37.7,0.73,1,0,0,0,0,0,-0.808840
212,212,Zimbabwe,6.0,1.0,50.1,18.15,0,0,0,0,0,1,-1.382121

3. Выберите в датафрейме строки, которые соответствуют странам Африки (afri) с
процентом женщин в парламенте (fparl08) выше 30%.

In [7]:
df[(df["fparl08"] > 30) & (df["afri"] == 1)]

,Unnamed: 0,ctry,fh09,polity09,gini,fparl08,mena,lati,cari,east,sovi,afri,corr0509
30,30,Burundi,4.5,6.0,33.3,31.74,0,0,0,0,0,1,-1.095802
133,133,Mozambique,3.5,5.0,47.1,34.80,0,0,0,0,0,1,-0.524405
160,160,Rwanda,5.5,-3.0,46.7,50.94,0,0,0,0,0,1,-0.164223
174,174,South Africa,2.0,9.0,57.8,33.92,0,0,0,0,0,1,0.332960
187,187,Tanzania,3.5,-1.0,34.6,30.41,0,0,0,0,0,1,-0.439213
198,198,Uganda,4.5,-1.0,42.6,30.72,0,0,0,0,0,1,-0.819751

4. Выберите в датафрейме строки, которые соответствуют странам Африки или
Латинской Америки (afri и lati) со значением индекса Polity2 (polity09) больше или
равным 8.

In [8]:
df[((df["afri"] == 1) | (df["lati"] == 1)) & (df["polity09"] >= 8)]

,Unnamed: 0,ctry,fh09,polity09,gini,fparl08,mena,lati,cari,east,sovi,afri,corr0509
7,7,Argentina,2.0,8.0,48.8,39.76,0,1,0,0,0,0,-0.420793
25,25,Botswana,2.5,8.0,61.0,11.11,0,0,0,0,0,1,0.947725
26,26,Brazil,2.0,8.0,55.0,9.43,0,1,0,0,0,0,-0.119536
39,39,Chile,1.0,10.0,52.0,12.66,0,1,0,0,0,0,1.370524
42,42,Comoros,3.5,9.0,64.3,3.03,0,0,0,0,0,1,-0.709136
45,45,Costa Rica,1.0,10.0,48.9,36.84,0,1,0,0,0,0,0.483973
54,54,Dominican Republic,2.0,8.0,48.4,17.14,0,1,0,0,0,0,-0.618924
57,57,El Salvador,2.5,8.0,46.9,16.67,0,1,0,0,0,0,-0.288100
71,71,Ghana,1.5,8.0,42.8,7.89,0,0,0,0,0,1,-0.031224
77,77,Guatemala,4.0,8.0,53.7,12.03,0,1,0,0,0,0,-0.681574
108,108,Lesotho,3.0,8.0,52.5,25.83,0,0,0,0,0,1,-0.028651
126,126,Mexico,2.5,8.0,51.6,22.13,0,1,0,0,0,0,-0.245729
141,141,Nicaragua,4.0,9.0,52.3,18.48,0,1,0,0,0,0,-0.747011
149,149,Panama,1.5,9.0,54.9,16.67,0,1,0,0,0,0,-0.311231
151,151,Paraguay,3.0,8.0,53.2,13.60,0,1,0,0,0,0,-1.190401
152,152,Peru,2.5,9.0,50.5,29.17,0,1,0,0,0,0,-0.310562
174,174,South Africa,2.0,9.0,57.8,33.92,0,0,0,0,0,1,0.332960
203,203,Uruguay,1.0,10.0,47.1,12.31,0,1,0,0,0,0,1.112514

5. Добавьте в датафрейм polit столбец corr_round, в котором будут храниться
округленные до 2 знака после запятой значения индекса Control of Corruption
(corr0509).

In [9]:
df["corr_round"] = df["corr0509"].apply(lambda x: round(x, 2))
df

,Unnamed: 0,ctry,fh09,polity09,gini,fparl08,mena,lati,cari,east,sovi,afri,corr0509,corr_round
1,1,Albania,3.0,9.0,33.0,7.14,0,0,0,0,1,0,-0.580513,-0.58
2,2,Algeria,5.5,2.0,35.3,6.48,1,0,0,0,0,0,-0.434654,-0.43
5,5,Angola,5.5,-2.0,58.6,37.27,0,0,0,0,0,0,-1.292684,-1.29
7,7,Argentina,2.0,8.0,48.8,39.76,0,1,0,0,0,0,-0.420793,-0.42
8,8,Armenia,5.0,5.0,30.2,8.40,0,0,0,0,0,0,-0.578211,-0.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,206,"Venezuela, RB",4.5,-3.0,43.4,18.56,0,1,0,0,0,0,-1.061680,-1.06
207,207,Vietnam,6.0,-7.0,37.8,25.76,0,0,0,1,0,0,-0.656128,-0.66
210,210,"Yemen, Rep.",5.5,-2.0,37.7,0.73,1,0,0,0,0,0,-0.808840,-0.81
211,211,Zambia,3.5,7.0,50.7,15.19,0,0,0,0,0,1,-0.601142,-0.60
212,212,Zimbabwe,6.0,1.0,50.1,18.15,0,0,0,0,0,1,-1.382121,-1.38

6. Добавьте в датафрейм polit столбец fh_status, в котором будут храниться типы стран
в зависимости от значения индекса Freedom House (значения free, partly free, not free).

In [11]:
fh_statuses = {
    "Free": [1, 2.75],
    "Partly Free": [2.75, 5.25],
    "Not Free": [5.25, 7]
}

def check_status(x):
    for st, rng in fh_statuses.items():
        if rng[0] < x <= rng[1]:
            return st
        
df["fh_status"] = df["fh09"].apply(check_status)
df[:5]

,Unnamed: 0,ctry,fh09,polity09,gini,fparl08,mena,lati,cari,east,sovi,afri,corr0509,corr_round,fh_status
1,1,Albania,3.0,9.0,33.0,7.14,0,0,0,0,1,0,-0.580513,-0.58,Partly Free
2,2,Algeria,5.5,2.0,35.3,6.48,1,0,0,0,0,0,-0.434654,-0.43,Not Free
5,5,Angola,5.5,-2.0,58.6,37.27,0,0,0,0,0,0,-1.292684,-1.29,Not Free
7,7,Argentina,2.0,8.0,48.8,39.76,0,1,0,0,0,0,-0.420793,-0.42,Free
8,8,Armenia,5.0,5.0,30.2,8.40,0,0,0,0,0,0,-0.578211,-0.58,Partly Free

7. Сгруппируйте строки в таблице в соответствии со значениями столбца fh_status,
полученного в предыдущей части и выведите минимальное, среднее и максимальное
значение показателя gini (индекс Джини) по каждой группе.

In [12]:
v = df.groupby(["fh_status"])
print(v.min()['gini'])
print(v.mean()['gini'])
print(v.max()['gini'])

fh_status
Free           24.9
Not Free       16.8
Partly Free    29.8
Name: gini, dtype: float64
fh_status
Free           42.406897
Not Free       39.750000
Partly Free    43.931250
Name: gini, dtype: float64
fh_status
Free           74.3
Not Free       58.6
Partly Free    64.3
Name: gini, dtype: float64

8. Сгруппируйте строки в таблице в соответствии со значениями столбца fh_status и
запишите строки, относящиеся к разным группам, в отдельные csv-файлы.

In [13]:
for name, status in v:
    status.to_csv(f"{name}.csv")