In [3]:
import pandas as pd
df = pd.read_csv("vgsales.csv")

1. Вывести все доступные платформы, на которых выпускалась хотя-бы одна игра;

In [4]:
df["Platform"].unique()

array(['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA',
       '3DS', 'PS4', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'XOne', 'GC',
       'WiiU', 'GEN', 'DC', 'PSV', 'SAT', 'SCD', 'WS', 'NG', 'TG16',
       '3DO', 'GG', 'PCFX'], dtype=object)

2. Добавить к копии набора данных столбец metacritic_rating и заполнить его данными
из набора данных Metacritic all time games stats

In [6]:
df_m = pd.read_csv("metacritic_games.csv")
df_merged = pd.merge(df, df_m, on=["Name"], how="inner")
df["metacritic_rating"] = df_merged["rating"]
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,metacritic_rating
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,E
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,E
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,E
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,E
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,E
...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,T
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,T
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,T
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,T
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,T

3. Вывести список игр, рейтинг которых равен "M" и год издания не ранее 2012 года;

In [7]:
games_2012 = df[(df["metacritic_rating"] == "M") & (df["Year"] >= 2012)]
games_2012

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,metacritic_rating
16,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40,M
23,24,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38,M
32,33,Pokemon X/Pokemon Y,3DS,2013.0,Role-Playing,Nintendo,5.17,4.05,4.34,0.79,14.35,M
33,34,Call of Duty: Black Ops 3,PS4,2015.0,Shooter,Activision,5.77,5.81,0.35,2.31,14.24,M
34,35,Call of Duty: Black Ops II,PS3,2012.0,Shooter,Activision,4.99,5.88,0.65,2.52,14.03,M
...,...,...,...,...,...,...,...,...,...,...,...,...
16550,16553,God Eater Off Shot: Tachibana Sakuya-hen Twin ...,PS4,2016.0,Action,Namco Bandai Games,0.00,0.00,0.01,0.00,0.01,M
16553,16556,Bound By Flame,X360,2014.0,Role-Playing,NaN,0.00,0.01,0.00,0.00,0.01,M
16570,16573,Farming 2017 - The Simulation,PS4,2016.0,Simulation,UIG Entertainment,0.00,0.01,0.00,0.00,0.01,M
16571,16574,Grisaia no Kajitsu: La Fruit de la Grisaia,PSP,2013.0,Adventure,Prototype,0.00,0.00,0.01,0.00,0.01,M
16589,16592,Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...,PSV,2016.0,Action,dramatic create,0.00,0.00,0.01,0.00,0.01,M

4. Рассчитать и вывести описательные статистики для списка, полученного в
предыдущем пункте

In [8]:
games_2012.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,491.000000,491.000000,491.000000,491.000000,491.000000,491.000000,491.000000
mean,8289.071283,2013.792261,0.419837,0.358737,0.109287,0.113401,1.001426
std,5653.494073,1.406117,1.084427,0.915775,0.403441,0.327679,2.376972
min,17.000000,2012.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,2412.500000,2012.000000,0.000000,0.000000,0.000000,0.000000,0.040000
50%,8103.000000,2014.000000,0.040000,0.040000,0.020000,0.010000,0.180000
75%,14078.500000,2015.000000,0.350000,0.250000,0.070000,0.080000,0.860000
max,16592.000000,2017.000000,9.630000,9.270000,4.360000,4.140000,21.400000

5. Вывести жанры игр с количеством игр, которые принадлежат соответствующему
жанру в виде "<жанр> - <количество игр>" для всех жанров, которые содержат в
своем названии не менее 3 различных гласных.

In [9]:
def check_vowels(x):
    vowels = ['a', 'e', 'i', 'o', 'u']
    count = 0
    for v in vowels:
        if v in x:
            count += 1
    if count >= 3:
        return True
    return False
        
genres = df[df["Genre"].apply(check_vowels)]
res = {}
for genre in genres["Genre"].unique():
    g = genres[genres["Genre"] == genre]
    res[genre] = g['Name'].count()

res

{'Role-Playing': 1488, 'Simulation': 867}